language: go

os:
  - linux

go:
  - 1.8

install:
  - make dependencies
  - test -z "$(go fmt ./...)"
  - make

script: make test && make test-long && make cover && make bench

sudo: false

branches:
  only:
    - master
    - wallet

notifications:
  email: false
